name: Greetings
on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - uses: actions/first-interaction@v1
        with:
          issue-message: Hi! Thank you for your contribution! Please re-check all
            issue template checklists - unfilled issues would be closed automatically.
            And do not forget to [join our slack](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw)
            for collaboration.
          pr-message: Hey thanks for the pull request! Please re-check all PR template
            checklists - unfilled PRs would be closed automatically. And do not forget
            to [join our slack](https://join.slack.com/t/catalyst-team-core/shared_invite/zt-d9miirnn-z86oKDzFMKlMG4fgFdZafw)
            for collaboration.
          repo-token: ${{ secrets.TOKEN_GITHUB }}
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
